### ISSUE TITLE
"ensuring similarity between groups by enforcing heterogeneity within groups"--what is the principle?

### ISSUE THREAD

**Issue by A-Pai** [m-Py/anticlust#63]
Paper "Using anticlustering to partition data sets into equivalent parts":
![image](https://github.com/user-attachments/assets/d525c2c9-56a7-4582-9584-69f855ff6822)
--what is the principle?
1. How to measure "similarity between groups" and  "heterogeneity within groups"?
2. Does increasing “heterogeneity within groups” necessarily cause  "similarity between groups" to decrease?

**Comment by A-Pai** [comment]
https://search.r-project.org/CRAN/refmans/anticlust/html/anticlustering.html
![image](https://github.com/user-attachments/assets/52e24946-b3fe-4a02-9a4a-8326f753b8eb)
it said “Note that the equivalence of within-group heterogeneity and between-group similarity only holds for equal-sized groups.”，so increasing “heterogeneity within groups” does not necessarily cause "similarity between groups" to decrease

**Comment by m-Py** [comment]
I will respond to this inquiry by the example of the diversity objective (which is mostly meant in the abstract, but I have to admit this is not explicit). 

> 1. How to measure "similarity between groups" and "heterogeneity within groups"?

We use the diversity objective, which is the overall sum between pairwise distances of elements assigned to the same (anti)cluster. It can be regarded as a measure of "heterogeneity within groups" because larger values indicate more dissimilarity between elements in the same groups. 

Maximizing the diversity simultaneously minimizes the sum of distances of elements in different clusters. That follows because the overall sum of distances is fixed, and elements are either in the same or in a different group. This was for example recognized by Feo and Khellaf (1990). Hence, similarity between groups is maximized. We were a little bit more explicit on explaining the motivation for using the diversity as criterion in the first version of our paper ([here](https://osf.io/download/5db99bfebc32f4000d0f4b67/?version=1&displayName=Preprint%20-%20Using%20anticlustering%20to%20partition%20a%20stimulus%20pool%20into%20equivalent%20parts%20(Papenberg,%20Klau)-2019-10-30T14%3A19%3A43.711Z.pdf)), so please check this out if you are more interested. See section ">Anticluster Editing". We shortened this section after peer review because, frankly, we had not been aware of the literature on the maximum diverse grouping problem, where the diversity objective had been discussed for a long time. So, there was no longer a need to argue for the usefulness of this objective because that had already been established.

> 2. Does increasing “heterogeneity within groups” necessarily cause "similarity between groups" to decrease?

It does for equal-sized groups. However, the diversity only equates between-group similarity and within-group heterogeneity for equal-sized groups, which we restricted our investigation to in Papenberg and Klau (2021). This is because the diversity is a mere sum and not an average, which incorporates information on group size. I am honestly not sure if (at least in the context of anticlustering) it has any merit at all for unequal-sized groups.

Feo, T. A., & Khellaf, M. (1990). A class of bounded approximation algorithms for graph partitioning. Networks, 20, 181--195.

Will close this issue, but feel free to post followup questions.

**Comment by A-Pai** [comment]
Are  "ensuring similarity between groups by enforcing heterogeneity within groups" and “Note that the equivalence of within-group heterogeneity and between-group similarity only holds for equal-sized groups.” in conflict?

**Comment by m-Py** [comment]
No, I would say these statements are not in conflict. That is because in the paper you are referring to  (Papenberg & Klau, 2021), we actually define / treat anticlustering as a problem that only creates equal-sized groups (see Problem Formalization (3) ). In this special case, maximizing the diversity always leads to increased between-group similarity. This no longer holds for unequal-sized groups, which we acknowledge in the paper (see Footnote 2), but I guess such nuance cannot always be given in an abstract (which you are quoting).

To give some more historic background: Originally, we were interested in minimizing between-group similarity, and only used the maximization of within-cluster heterogeneity because it is equivalent to minimizing between-group similarity for equal-sized groups (e.g., see this presentation from 2019 in London https://osf.io/jbthk). 

We originally even considered keeping a normalizing factor for group sizes but dropped it because we were only interested in applications with equal group sizes (see section 2.1 and 2.2 in https://www.cs.hhu.de/fileadmin/redaktion/Fakultaeten/Mathematisch-Naturwissenschaftliche_Fakultaet/Informatik/Algorithmische_Bioinformatik/Bachelor-_Masterarbeiten/BA-Papenberg.pdf). Moreover, dropping the factor that normalizes for group sizes makes the problem "easier" to solve using frameworks such as integer linear programming, which we were interested in. Interestingly, the "mere sum diversity" is also the objective used in the maximal diverse grouping problem and I don't see that anyone has ever discussed its problem with unequal-sized groups (if you find something, please tell me). 

Later, I acknowledged that restricting anticlustering to equal-sized groups may be too restricting, even though I personally have not seen an application where I would require different-sized groups, [some issues in this Github repository](https://github.com/m-Py/anticlust/issues/49) suggest that others have such use cases. In the k-plus paper (Papenberg, 2024) I explicitly discuss the diversity and k-means / k-plus objectives in the context of different-sized groups and show that the mere diversity is not useful here. This is my opinion because maximizing the diversity does not lead to between-group similarity and I am really not even sure what it measures then. It seems that it creates one big heterogeneous cluster and other smaller homogeneous clusters. I would not know in which context I would want that. 

So, I am seriously considering making the "average-diversity" the default objective in `anticlustering()` in an upcoming version of `anticlust`; it does not make a difference for the default case of equal-sized groups, but it should generally improve results for unequal-sized groups.
