### ISSUE TITLE
"Minimizing the k-means criterion simultaneously maximizes between-cluster separation and within-cluster homogeneity",What is the basis?

### ISSUE THREAD

**Issue by A-Pai** [m-Py/anticlust#64]
paper "K-Plus anticlustering_ An improved k-means criterion for maximizing between-group similarity"
![image](https://github.com/user-attachments/assets/198fa276-c9e9-4840-a597-65fe9cb50d41)

"Minimizing the k-means criterion simultaneously maximizes between-cluster separation and within-cluster homogeneity",What is the basis? I can not find the proof at its reference(Aloise, D., Deshpande, A., Hansen, P., & Popat, P. (2009). NP-hardness of Euclidean sum-of-squares clustering. Machine Learning, 75(2), 245–248. https://doi.org/10.1007/s10994-009-5103-0)

**Comment by m-Py** [comment]
I actually refer to the first paragraph in that paper, where we have

> One key criterion is the minimum sum of squared Euclidean distances from each entity to the centroid of the cluster to which it belongs, which expresses both homogeneity and separation.

But you are right, I suppose they do no include a proof of this statement. I believe a proof is found in Späth (1986), who I also refer to for this result. Späth showed that maximizing the total  within-cluster variance (i.e., homogeneity) leads to minimum distance between cluster centroids (i.e., separation), and vice versa.

Späth, H. (1986). Anticlustering: Maximizing the variance criterion. *Control and Cybernetics, 15*, 213--218.

When we introduce constraints on group sizes (which we usually do in the context of anticlustering), we lose the strict result with regard to global maximum in distance / variance, but the duality of homogeneity / separation remains. In fact, in `fast_anticlustering()`, I use this result because minimizing the distance between cluster centers can be accomplished faster than maximizing the variance within clusters.

Closing this issue but feel free to post followup questions.
